sudo: required
dist: trusty
language: python
python:
  - "2.7_with_system_site_packages"
before_install:
  - sudo apt-add-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update -q
  - sudo apt-get install --no-install-recommends --no-upgrade -qq bitcoind
install:
  - ./install.sh
before_script:
  - source jmvenv/bin/activate
script:
  - ./test/run_tests.sh
after_success:
  - coveralls
branches:
 only:
  - master
  - test_travis
