sudo: required
services: docker
language: python
python:
  - "2.7_with_system_site_packages"
install:
  - docker pull ubuntu:trusty
script:
  - docker build --shm-size=1G .
after_success:
  - echo "Success !"
branches:
 only:
  - master
  - test_travis
